---
version: "3"
services:
  splinter-sniper:
    image: danops/splinter-sniper
    container_name: splinter-sniper
    environment:
      - HIVE_USERNAME=$HIVE_USERNAME
      - HIVE_ACTIVE_KEY=$HIVE_ACTIVE_KEY
      - TZ=Europe/Madrid
      - OTEL_SERVICE_NAME=splinter-sniper
      - OTEL_RESOURCE_ATTRIBUTES=app=splinter-sniper
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
      - OTEL_PROPAGATORS=tracecontext

    restart: unless-stopped
    volumes:
      - type: bind
        source: ./logs
        target: /usr/app/src/logs
      - type: bind
        source: ./config.json
        target: /usr/app/src/config.json

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    environment:
      - TEMPO_USERNAME=$TEMPO_USERNAME
      - GRAFANA_KEY=$GRAFANA_KEY
      - TEMPO_BASIC_AUTH=$TEMPO_BASIC_AUTH
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector.yaml
    ports:
      - "4318:4318"
      - "4317:4317"
    restart: unless-stopped
